// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vaccine.Domain;

#nullable disable

namespace vaccine.Domain.Migrations
{
    [DbContext(typeof(VaccineDbContext))]
    [Migration("20251226230838_SeedDataForVaccination")]
    partial class SeedDataForVaccination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vaccine.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Dose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<short>("DoseType")
                        .HasColumnType("smallint")
                        .HasColumnName("dose_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VaccinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("vaccination_id");

                    b.HasKey("Id");

                    b.HasIndex("VaccinationId");

                    b.ToTable("dose", (string)null);
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("document");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("person", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8cf44a3d-1700-4167-ab56-66a65c5817ba"),
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1990, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Document = "99711606097",
                            Name = "Eduarda Marino"
                        },
                        new
                        {
                            Id = new Guid("dfc67e0d-3ac4-4b81-8ec4-8ec90da29546"),
                            Birthday = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Document = "06693964001",
                            Name = "João Silva"
                        },
                        new
                        {
                            Id = new Guid("46bdd486-3de7-4977-af3a-200a7ba02773"),
                            Birthday = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Document = "02443959007",
                            Name = "Maria Oliveira"
                        },
                        new
                        {
                            Id = new Guid("8ce58e9d-81b3-4aa3-a097-396b46175865"),
                            Birthday = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Document = "75251000049",
                            Name = "Carlos Pereira"
                        },
                        new
                        {
                            Id = new Guid("322c1393-bd8e-4fb6-b074-b8764a16d317"),
                            Birthday = new DateTime(1995, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(1995, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Document = "09712058093",
                            Name = "Ana Costa"
                        });
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Vaccination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VaccineId")
                        .HasColumnType("uuid")
                        .HasColumnName("vaccine_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("VaccineId");

                    b.ToTable("vaccination", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("186ce810-ba7e-4ec1-84bd-094003988c3b"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            PersonId = new Guid("8cf44a3d-1700-4167-ab56-66a65c5817ba"),
                            VaccineId = new Guid("74c6d6e2-f3ad-4ea8-97ec-6fa900425519")
                        },
                        new
                        {
                            Id = new Guid("501239da-1ccb-4540-bda4-2ccb4a89db9f"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            PersonId = new Guid("46bdd486-3de7-4977-af3a-200a7ba02773"),
                            VaccineId = new Guid("7def8280-c204-49ce-b04c-e3631a9e414f")
                        });
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AvailableTypes")
                        .HasColumnType("smallint")
                        .HasColumnName("available_types");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("vaccine", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("74c6d6e2-f3ad-4ea8-97ec-6fa900425519"),
                            AvailableTypes = (short)7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Name = "Hepatite B"
                        },
                        new
                        {
                            Id = new Guid("7def8280-c204-49ce-b04c-e3631a9e414f"),
                            AvailableTypes = (short)27,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Name = "COVID-19"
                        },
                        new
                        {
                            Id = new Guid("63f8f8de-1772-4220-ab07-d00f3748a4c9"),
                            AvailableTypes = (short)1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Name = "Influenza (Gripe)"
                        },
                        new
                        {
                            Id = new Guid("05df7267-b874-42b2-944d-7c04c100d85e"),
                            AvailableTypes = (short)1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Name = "Febre Amarela"
                        },
                        new
                        {
                            Id = new Guid("45e171d4-e07a-42c9-973d-68d947b86b9f"),
                            AvailableTypes = (short)3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("efbc569d-c8ad-463a-9158-27cdb8d8630a"),
                            Name = "Tríplice Viral (Sarampo, Caxumba, Rubéola)"
                        });
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Dose", b =>
                {
                    b.HasOne("vaccine.Domain.Entities.Vaccination", "Vaccination")
                        .WithMany("Doses")
                        .HasForeignKey("VaccinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccination");
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Person", b =>
                {
                    b.HasOne("vaccine.Data.Entities.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("vaccine.Domain.Entities.Person", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Vaccination", b =>
                {
                    b.HasOne("vaccine.Domain.Entities.Person", "Person")
                        .WithMany("Vaccinations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vaccine.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany("Vaccinations")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("vaccine.Data.Entities.User", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Person", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Vaccination", b =>
                {
                    b.Navigation("Doses");
                });

            modelBuilder.Entity("vaccine.Domain.Entities.Vaccine", b =>
                {
                    b.Navigation("Vaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
